// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzrbmcozoouvyonsvbxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cmJtY296b291dnlvbnN2YnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjk3NzksImV4cCI6MjA2OTgwNTc3OX0.NBAtyenoYjGrtbVUT75L4nw6IG5GMTbyCopAr51oS_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});